server:
  port: 8081
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    allow-redirects: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
